import datetime

FILE_HEADER_LINES = [
    "  -------------------------------------------------------------------- ",
    " |                             DO NOT EDIT                            |",
    " |          This file is automatically generated by a script.         |",
    "  -------------------------------------------------------------------- ",
]

def getHeaderLines(comment_char:str, file_name:str=None):
    lines = []
    for line in FILE_HEADER_LINES:
        lines.append(f'{comment_char} {line}')
    lines.append(f"{comment_char} Generated: " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    if file_name:
        lines.append(f"{comment_char} File: {file_name}")
    return lines


def getFooterLines(comment_char:str):
    lines = []
    for line in FILE_HEADER_LINES:
        lines.append(f'{comment_char} {line}')
    return lines