//   -------------------------------------------------------------------- 
//  |                             DO NOT EDIT                            |
//  |          This file is automatically generated by a script.         |
//   -------------------------------------------------------------------- 
// Generated: 2023-08-29 07:11:41
// File: packet_ids.hpp

#ifndef PACKET_IDS_HPP_
#define PACKET_IDS_HPP_

#include <cstdint>

enum class PacketId : uint8_t {
  UNKNOWN = 0x00, // Unknown Packet Type
  HANDSHAKE = 0x01, // Handshake Packet
  ERROR = 0x02, // Error Packet
  ACK = 0x03 // Acknowledge Packet
};

enum class ErrorId : uint8_t {
  UNKNOWN = 0x00, // Unknown Error
  INVALID_START_FLAG = 0x01, // The start flag of the packet was invalid
  INVALID_PACKET_ID = 0x02 // The ID of the packet was invalid
};

#endif // PACKET_IDS_HPP_

//   -------------------------------------------------------------------- 
//  |                             DO NOT EDIT                            |
//  |          This file is automatically generated by a script.         |
//   -------------------------------------------------------------------- 