#   -------------------------------------------------------------------- 
#  |                             DO NOT EDIT                            |
#  |          This file is automatically generated by a script.         |
#   -------------------------------------------------------------------- 
# Generated: 2023-09-09 19:39:15
# File: external_comms_types.py

from enum import IntEnum

class MessageId(IntEnum):
    UNKNOWN = 0x00 # Unknown Packet Type
    HANDSHAKE = 0x01 # Handshake Packet
    ERROR = 0x02 # Error Packet
    ACK = 0x03 # Acknowledge Packet
    SET_AAR = 0x04 # Set the AAR of the timer

class ErrorId(IntEnum):
    UNKNOWN = 0x00 # Unknown Error
    INVALID_START_FLAG = 0x01 # The start flag of the packet was invalid
    INVALID_PACKET_ID = 0x02 # The ID of the packet was invalid
    INVALID_PAYLOAD_SIZE = 0x03
    INVALID_CRC = 0x04
    INVALID_END_FLAG = 0x05
    MESSAGE_TIMED_OUT = 0x06
    BUSY = 0x07
    INVALID_PAYLOAD_FOR_MESSAGE_TYPE = 0x08

#   -------------------------------------------------------------------- 
#  |                             DO NOT EDIT                            |
#  |          This file is automatically generated by a script.         |
#   -------------------------------------------------------------------- 