#   -------------------------------------------------------------------- 
#  |                             DO NOT EDIT                            |
#  |          This file is automatically generated by a script.         |
#   -------------------------------------------------------------------- 
# Generated: 2023-09-07 10:13:07
# File: external_comms_types.py

from enum import IntEnum

class PacketId(IntEnum):
    UNKNOWN = 0x00 # Unknown Packet Type
    HANDSHAKE = 0x01 # Handshake Packet
    ERROR = 0x02 # Error Packet
    ACK = 0x03 # Acknowledge Packet
    INC = 0x04 # Increase Frequency Packet
    DEC = 0x05 # Decrease Frequency Packet

class ErrorId(IntEnum):
    UNKNOWN = 0x00 # Unknown Error
    INVALID_START_FLAG = 0x01 # The start flag of the packet was invalid
    INVALID_PACKET_ID = 0x02 # The ID of the packet was invalid

#   -------------------------------------------------------------------- 
#  |                             DO NOT EDIT                            |
#  |          This file is automatically generated by a script.         |
#   -------------------------------------------------------------------- 