@startuml

state "Idle" as Idle
state "Transmit Mode" as Transmitting {
  state "Starting Tx" as StartingTx
  state "Tx Preamble" as TxPreamble
  state "Tx Data" as TxData

  [*] --> StartingTx
  StartingTx --> TxPreamble
  StartingTx --> TxData : No preamble configured
  TxPreamble --> TxData
  TxData --> [*]

}
state "Receiving" as Receiving 

[*] --> Idle
Idle --> Transmitting : Commanded to send a packet via UART
Idle --> Receiving : Commanded to enter receive mode

@enduml