name: STM32 Modem - Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Prerequisites
        run: |
          apt-get update
          apt-get install gcc-arm-none-eabi ninja-build -y